"""Score the HELD-OUT-PERSONA conversations on both graders (added 2026-10-08).

The held-out set is 48 personas with a problem the training grid never had (alcohol;
``system_prompts_builder.generate_heldout_permutations``), generated by
``code/tools/generate_eval_convs.py --personas alcohol --conv-dir ...`` for four model states
(the untrained Base, K=0 at iterations 8 and 10, K=5 at 10) into
``data/grpo_Exp3/conversations/heldout_alcohol/<EXP_NAME>/model_iter_<N>_TT*_TP*/`` -- outside
``conversations/full/``, so ``discover_arms`` never sees them. As for the replicate draw
(``score_replicate.py``), this script builds the manual :class:`Experiment` entries, with the set
marker as an infix in the lake model name (``GRPOExp3_LA0_alc_I8``), so held-out scores can never
collide with the training-grid scores of the same state.

All nine scoring calls per conversation (the eight instruments and the MIPROC utterance coder;
the reported PCT is derived from MIPROC), both graders, ``rep=0``. Resume-safe per CSV:

    python tools/score_heldout.py --coverage           # count CSVs on disk, score nothing (free)
    python tools/score_heldout.py --primary            # gpt-4o-mini, live (the training oracle)
    python tools/score_heldout.py --judge              # claude-haiku-4-5, live (the held-out judge)

Cost: 4 states x 48 conversations x 9 calls = 1,728 calls per grader (about $2 for the training
oracle, about $10 for the held-out judge at live rates). Analysis: ``tools/heldout_check.py``.
"""

from __future__ import annotations

import argparse
import asyncio
import os
import sys

_p = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
if _p not in sys.path:
    sys.path.insert(0, _p)

from eda_analysis.scoring import (  # noqa: E402
    WORKSPACE_ROOT, ScoringConfig, EVAL_QUESTIONNAIRE_DIRS,
    get_model_eval_layout, load_data, combine_data, add_model_metadata_columns, eval_csv_dir,
    eval_scores_root,
)
from eda_analysis.scoring.registry import Experiment  # noqa: E402
from eda_analysis.scoring import pipeline as oracle_eval  # noqa: E402
from eda_analysis.scoring.judge import JudgeSpec, run_judge_scoring  # noqa: E402

N_PERSONAS = 48
_LA0 = "GRPO_Iterative_Q1Q2_Llama32-1B_LA0_MCL12_G8"
_LA5 = "GRPO_Iterative_Q1Q2_Llama32-1B_LA5_MCL12_G8"


def _path(exp_name: str, k: int) -> str:
    return os.path.join("data", "grpo_Exp3", "conversations", "heldout_alcohol", exp_name,
                        f"model_iter_{k}_TT0.9_TP0.7")


# One manual Experiment per held-out state. The Base is one draw (generated under the K=0 run's
# config; it has no adapter, so the run does not matter), oracle "Base" -> lake folder oracle=none.
HELDOUT = [
    Experiment(oracle="Base", lookahead=0, version=None, method="GRPO_Exp3", epoch=0,
               path=_path(_LA0, 0), model_name_override="GRPOExp3_LA0_alc_Base"),
    Experiment(oracle="Q1Q2", lookahead=0, version=None, method="GRPO_Exp3", epoch=8,
               path=_path(_LA0, 8), model_name_override="GRPOExp3_LA0_alc_I8"),
    Experiment(oracle="Q1Q2", lookahead=0, version=None, method="GRPO_Exp3", epoch=10,
               path=_path(_LA0, 10), model_name_override="GRPOExp3_LA0_alc_I10"),
    Experiment(oracle="Q1Q2", lookahead=5, version=None, method="GRPO_Exp3", epoch=10,
               path=_path(_LA5, 10), model_name_override="GRPOExp3_LA5_alc_I10"),
]

JUDGE = JudgeSpec(provider="anthropic", model="claude-haiku-4-5")   # tag: anthropic_claude-haiku-4-5


def _load_combined():
    """Load every held-out state whose 48 conversations are all on disk (others are skipped)."""
    ready, skipped = [], []
    for e in HELDOUT:
        p = os.path.join(WORKSPACE_ROOT, e.path)
        n = len([f for f in os.listdir(p) if f.startswith("conversation_")]) if os.path.isdir(p) else 0
        done = n >= N_PERSONAS
        print(f"  {e.model_name}: {n}/{N_PERSONAS} conversation CSV(s)" + ("" if done else "   <-- not complete, SKIPPED"))
        (ready if done else skipped).append(e)
    if not ready:
        raise SystemExit("No held-out state is complete yet -- nothing to score.")
    if skipped:
        print(f"  ! scoring {len(ready)} of {len(HELDOUT)} states; re-run once the rest finish.")
    combined = combine_data(load_data([os.path.join(WORKSPACE_ROOT, e.path) for e in ready]),
                            [e.model_name for e in ready])
    combined["id"] = combined["id"].astype(int)
    combined = add_model_metadata_columns(combined)
    print(f"  -> {len(combined)} conversations, models: {sorted(combined['Model'].unique())}")
    return combined, ready


def _coverage(judge_tag: str, rep: int = 0) -> None:
    root = eval_scores_root(judge_tag, rep)
    label = judge_tag or "primary"
    for e in HELDOUT:
        counts = []
        for qname, subdir in EVAL_QUESTIONNAIRE_DIRS.items():
            d = eval_csv_dir(root, e.oracle_label, subdir, e.model_name)
            counts.append(f"{qname}:{len(os.listdir(d)) if os.path.isdir(d) else 0}")
        print(f"  [{label}] {e.model_name}: " + "  ".join(counts))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--primary", action="store_true", help="score with the training oracle (live)")
    ap.add_argument("--judge", action="store_true", help="score with the held-out judge (live)")
    ap.add_argument("--coverage", action="store_true", help="report CSV counts and exit")
    ap.add_argument("--concurrency", type=int, default=None)
    args = ap.parse_args()

    if args.coverage:
        _coverage("");  _coverage(JUDGE.tag)
        return 0
    if not (args.primary or args.judge):
        ap.error("pass --primary and/or --judge (or --coverage)")

    assert oracle_eval.EVAL_CODE_AVAILABLE, "questionnaires module not importable (code/ off sys.path?)"
    combined, ready = _load_combined()
    layout = get_model_eval_layout(ready)

    if args.primary:
        from openai import AsyncOpenAI
        with open(os.path.join(WORKSPACE_ROOT, "openai_key.txt")) as fh:
            client = AsyncOpenAI(api_key=fh.read().strip())
        cfgs = oracle_eval.build_default_eval_configs(ScoringConfig())
        print(f"\n== PRIMARY (gpt-4o-mini, live): {len(ready)} state(s) x {len(cfgs)} calls x {N_PERSONAS} ==")
        stats = asyncio.run(oracle_eval.run_all_evaluations_async(
            client, combined, cfgs, layout, concurrency=args.concurrency or 32))
        print({k: v for k, v in stats.items()})

    if args.judge:
        print(f"\n== HELD-OUT JUDGE ({JUDGE.tag}, live): {len(ready)} state(s) x "
              f"{len(EVAL_QUESTIONNAIRE_DIRS)} calls x {N_PERSONAS} ==")
        stats = asyncio.run(run_judge_scoring(
            JUDGE, combined, list(EVAL_QUESTIONNAIRE_DIRS), layout,
            rep=0, concurrency=args.concurrency or 16))
        print(stats)

    print("\ncoverage after this run:")
    _coverage("");  _coverage(JUDGE.tag)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
