"""Score the REPLICATE conversation draws on both graders (STATUS.md § replicate draw).

A replicate is a second independent 96-conversation sample of an already-scored model state,
generated by ``code/tools/generate_eval_convs.py --conv-dir`` into
``data/<method>_Exp3/conversations/replicate/<EXP_NAME>/model_iter_<N>_rep1_TT*_TP*/`` — outside
``conversations/full/``, so ``discover_arms`` (and with it every notebook, ``Run_Eval``'s
auto-registry, and the multi-judge coverage tables) never sees it. This script is the explicit
scoring path for those dirs: it builds the manual :class:`Experiment` entries the auto-registry
cannot, with the draw marker as an infix in the lake model name (``GRPOExp3_LA5_rep1_I10``) so the
replicate and the primary draw can never collide in ``eval_scores/``.

Phases (both resume-safe — existing per-conversation CSVs are skipped):
    python tools/score_replicate.py --primary        # gpt-4o-mini, live (the training oracle)
    python tools/score_replicate.py --judge          # claude-haiku-4-5, live (the held-out judge)
    python tools/score_replicate.py --primary --judge
    python tools/score_replicate.py --coverage       # count CSVs on disk, score nothing

Cost: 2 states x 8 instruments x 96 conversations = 1,536 calls per grader.
Analysis lives in ``tools/replicate_check.py`` (run it after both graders are complete).
"""

from __future__ import annotations

import argparse
import asyncio
import os
import sys

_p = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
if _p not in sys.path:
    sys.path.insert(0, _p)

from eda_analysis.scoring import (  # noqa: E402
    WORKSPACE_ROOT, ScoringConfig, EVAL_QUESTIONNAIRE_DIRS,
    get_model_eval_layout, load_data, combine_data, add_model_metadata_columns, eval_csv_dir,
    eval_scores_root,
)
from eda_analysis.scoring.registry import Experiment  # noqa: E402
from eda_analysis.scoring import pipeline as oracle_eval  # noqa: E402
from eda_analysis.scoring.judge import JudgeSpec, run_judge_scoring  # noqa: E402


# ── The replicate registry: one manual Experiment per replicate draw on disk. ─────────────────
# ``model_name_override`` carries the draw marker as an infix BEFORE the _I<k> tail (STATUS.md);
# ``path`` is experiment-root-relative like every auto-generated entry.
REPLICATES = [
    Experiment(
        oracle="Q1Q2", lookahead=5, version=None, method="GRPO_Exp3", epoch=10,
        path=os.path.join("data", "grpo_Exp3", "conversations", "replicate",
                          "GRPO_Iterative_Q1Q2_Llama32-1B_LA5_MCL12_G8",
                          "model_iter_10_rep1_TT0.9_TP0.7"),
        model_name_override="GRPOExp3_LA5_rep1_I10",
    ),
    Experiment(
        oracle="Q1Q2", lookahead=0, version=None, method="PTO_Exp3", epoch=10,
        path=os.path.join("data", "pto_Exp3", "conversations", "replicate",
                          "PTO_Iterative_Q1Q2_Llama32-1B_LA0_MCL12_M8_PTgreedy",
                          "model_iter_10_rep1_TT0.9_TP0.7"),
        model_name_override="PTOExp3_LA0_rep1_I10",
    ),
]

HELDOUT = JudgeSpec(provider="anthropic", model="claude-haiku-4-5")   # tag: anthropic_claude-haiku-4-5


def _load_combined():
    """Load every replicate whose 96 conversations are all on disk.

    A draw that is still generating is SKIPPED with a warning rather than failing the run, so the
    first finished draw can be scored while the second is still on Colab. Scoring is resume-safe
    per conversation CSV, so re-running once the second lands scores only the new work.
    """
    ready, skipped = [], []
    for e in REPLICATES:
        p = os.path.join(WORKSPACE_ROOT, e.path)
        n = len([f for f in os.listdir(p) if f.startswith("conversation_")]) if os.path.isdir(p) else 0
        print(f"  {e.model_name}: {n}/96 conversation CSV(s)" + ("" if n >= 96 else "   <-- still generating, SKIPPED"))
        (ready if n >= 96 else skipped).append(e)
    if not ready:
        raise SystemExit("No replicate draw is complete yet — nothing to score.")
    if skipped:
        print(f"  ! scoring {len(ready)} of {len(REPLICATES)} draws; re-run this script once "
              f"{', '.join(e.model_name for e in skipped)} finishes.")
    combined = combine_data(load_data([os.path.join(WORKSPACE_ROOT, e.path) for e in ready]),
                            [e.model_name for e in ready])
    combined["id"] = combined["id"].astype(int)
    combined = add_model_metadata_columns(combined)
    print(f"  -> {len(combined)} conversations, models: {sorted(combined['Model'].unique())}")
    return combined, ready


def _coverage(judge_tag: str, rep: int = 0) -> None:
    root = eval_scores_root(judge_tag, rep)
    label = judge_tag or "primary"
    for e in REPLICATES:
        counts = []
        for qname, subdir in EVAL_QUESTIONNAIRE_DIRS.items():
            d = eval_csv_dir(root, e.oracle_label, subdir, e.model_name)
            counts.append(f"{qname}:{len(os.listdir(d)) if os.path.isdir(d) else 0}")
        print(f"  [{label}] {e.model_name}: " + "  ".join(counts))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--primary", action="store_true", help="score with the training oracle (live)")
    ap.add_argument("--judge", action="store_true", help="score with the held-out judge (live)")
    ap.add_argument("--coverage", action="store_true", help="report CSV counts and exit")
    ap.add_argument("--concurrency", type=int, default=None)
    args = ap.parse_args()

    if args.coverage:
        _coverage("");  _coverage(HELDOUT.tag)
        return 0
    if not (args.primary or args.judge):
        ap.error("pass --primary and/or --judge (or --coverage)")

    assert oracle_eval.EVAL_CODE_AVAILABLE, "questionnaires module not importable (code/ off sys.path?)"
    combined, ready = _load_combined()
    layout = get_model_eval_layout(ready)   # {model_name: {'root': primary rep=0, 'oracle': 'Q1Q2'}}

    if args.primary:
        from openai import AsyncOpenAI
        with open(os.path.join(WORKSPACE_ROOT, "openai_key.txt")) as fh:
            client = AsyncOpenAI(api_key=fh.read().strip())
        cfgs = oracle_eval.build_default_eval_configs(ScoringConfig())
        print(f"\n== PRIMARY (gpt-4o-mini, live): {len(ready)} model(s) x {len(cfgs)} instruments x 96 ==")
        stats = asyncio.run(oracle_eval.run_all_evaluations_async(
            client, combined, cfgs, layout, concurrency=args.concurrency or 32))
        print({k: v for k, v in stats.items()})

    if args.judge:
        print(f"\n== HELD-OUT ({HELDOUT.tag}, live): {len(ready)} model(s) x 8 instruments x 96 ==")
        stats = asyncio.run(run_judge_scoring(
            HELDOUT, combined, list(EVAL_QUESTIONNAIRE_DIRS), layout,
            rep=0, concurrency=args.concurrency or 16))
        print(stats)

    print("\ncoverage after this run:")
    _coverage("");  _coverage(HELDOUT.tag)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
