"""Generate ``requirements.txt`` from the curated top-level dependency list.

Why not just ``pip freeze``?
- ``pip freeze`` dumps every transitive dep (~150+ lines) and platform-specific
  pins (``pywin32`` etc.) which makes the file unreadable and Linux-hostile.
- This script lists only the packages the project *directly* imports, grouped
  by purpose, with a one-line note for each group. Versions are pulled from
  whatever is installed in the current environment via :mod:`importlib.metadata`.

Run:
    python gen_requirements.py

Produces a single ``requirements.txt`` at this script's location.
"""

from importlib.metadata import PackageNotFoundError, version
from pathlib import Path
from typing import Dict, List

HERE = Path(__file__).parent


# Top-level direct dependencies, grouped for readability in the output file.
# Pinning is exact (== <installed_version>); to relax, edit requirements.txt
# after generation.
GROUPS: Dict[str, List[str]] = {
    "Core scientific stack": [
        "numpy", "pandas", "scipy", "statsmodels",
        "matplotlib", "seaborn", "scikit-learn",
    ],
    "Notebook + I/O": [
        "jupyter", "ipykernel", "ipywidgets",
        "nbformat", "nbconvert",
        "tqdm",
    ],
    "OpenAI client (oracle scoring + patient simulator)": [
        "openai",
    ],
    "Hugging Face training stack — Exp3 GRPO V2 (GPU)": [
        # torch is intentionally omitted: it must be installed from the CUDA
        # wheel index, not PyPI. See the header note in requirements.txt.
        "transformers", "trl", "peft", "accelerate",
        "datasets", "huggingface_hub", "safetensors",
        "bitsandbytes",
    ],
    "Experiment tracking": [
        "wandb", "tensorboard",
    ],
    "Preference-embedding analysis (eda/pref_emb)": [
        "sentence-transformers", "wordfreq", "nltk",
    ],
}


TORCH_NOTE = (
    "# ─────────────────────────────────────────────────────────────────────────\n"
    "# torch is NOT pinned here — install it from the CUDA wheel index that\n"
    "# matches your driver, e.g.:\n"
    "#\n"
    "#     pip install torch --index-url https://download.pytorch.org/whl/cu128\n"
    "#\n"
    "# (Use cu121 / cu118 for older drivers, or drop the --index-url flag for\n"
    "# the CPU-only build.) Then re-run ``python gen_requirements.py`` so the\n"
    "# installed torch version is recorded in the comment below.\n"
    "# ─────────────────────────────────────────────────────────────────────────\n"
)


def _resolve_version(name: str) -> str:
    try:
        return version(name)
    except PackageNotFoundError:
        return ""


def main() -> None:
    out_lines: List[str] = []
    out_lines.append("# requirements.txt — generated by gen_requirements.py")
    out_lines.append("# Versions reflect what's currently installed in the active environment.")
    out_lines.append("")
    out_lines.append(TORCH_NOTE)

    # Show whatever torch version is installed, as a comment (not a pin).
    torch_v = _resolve_version("torch")
    if torch_v:
        out_lines.append(f"# Currently installed: torch=={torch_v}")
        out_lines.append("")

    n_total = 0
    n_missing = 0
    for label, deps in GROUPS.items():
        out_lines.append(f"# {label}")
        for name in deps:
            v = _resolve_version(name)
            n_total += 1
            if v:
                out_lines.append(f"{name}=={v}")
            else:
                out_lines.append(f"# {name}   (not installed in current env)")
                n_missing += 1
        out_lines.append("")

    (HERE / "requirements.txt").write_text("\n".join(out_lines), encoding="utf-8")
    print(f"Wrote requirements.txt — {n_total - n_missing}/{n_total} packages pinned, "
          f"{n_missing} not yet installed.")
    if torch_v:
        print(f"  torch=={torch_v} recorded as comment (install via CUDA index).")
    else:
        print("  torch not detected — install it before running again to record the version.")


if __name__ == "__main__":
    main()
