"""grpo_trainer.py -- the pieces one GRPO iteration is composed from.

The orchestration LOOP lives in ``train_grpo.ipynb``, visibly, where a human can read what the
run is about to do. This module holds the functions that loop calls, and nothing else: there is
deliberately no ``run_iterative_training`` here. Exp3 had one, it duplicated the notebook loop,
and the two drifted -- the notebook grew a look-ahead state and a TB logger the convenience
wrapper never learned about, so calling it silently ran a different experiment.

One iteration, in the order the functions appear below:

1. **Generate.** The current policy simulates ``num_conversations_per_iter`` conversations
   against the patient simulator, one per persona, into
   ``conversations/<ARM>/model_iter_{n-1}/``. Those conversations ARE the eval set for model
   state ``n-1``; there is no separate eval pass, which is why the folder is named after the
   policy that GENERATED it and not after the iteration that consumed it.
2. **Extract prompts.** Slice each conversation after every patient turn whose
   conversation-so-far has at least ``MIN_CONV_LENGTH`` utterances. Each slice carries the
   chat-templated ``prompt`` TRL samples from and the plain-text ``transcript`` the oracle
   grades, plus the ids look-ahead needs to continue against the right patient.
3. **Train.** ``GRPOTrainer`` samples ``G`` completions per prompt, the reward function scores
   each one (through the K-turn look-ahead when ``K > 0``), advantages are group-relative
   ``(r - mean)/std`` over the G siblings, and the loss is a PPO-style clip plus a KL penalty
   against the iteration's reference -- the adapter as it stood when the iteration started.
4. **Save.** Per-epoch checkpoints under ``iteration_N/training/``, the final adapter at
   ``iteration_N/adapter/``, whose EXISTENCE is the definition of "this iteration is done".

Five things in here are load-bearing and look like details
----------------------------------------------------------
**LoRA is attached BEFORE the trainer, never handed to it as ``peft_config``.** The reward
closure captures the policy object so that look-ahead rolls out under the weights being trained.
If the trainer were the one to wrap the model, the closure would hold the *unwrapped base* and
every look-ahead turn of the first iteration would be generated by a policy with no adapter --
silently, since a freshly-initialised LoRA is numerically identity at step 0 and only diverges as
training proceeds. :func:`ensure_peft_policy` closes that gap, and it runs AFTER generation so
that ``model_iter_0`` really is the untrained base.

**``per_device_train_batch_size`` counts COMPLETIONS, not prompts**, and
``gradient_accumulation_steps`` must never be collapsed to 1. Both are spelled out at the config
site in :func:`build_grpo_config`, which is where somebody would otherwise "optimise" them.

**The EDA recorder is reloaded from the checkpoint on resume.** HuggingFace resumes by
fast-forwarding through batches that were already consumed, and a fast-forwarded batch never
re-invokes the reward function. Without the snapshot reload an interrupted iteration's
``generations.jsonl`` silently contains only the rows produced after the resume point.

**Timing is written through ``core.timing.log_session``, and that is the ONLY timing record.**
Exp3's per-process fields undercounted a resumed iteration by up to 2x and cost 1,336 LOC of
artifact-mtime archaeology to repair. Every phase this module measures gets logged; nothing is
reconstructed later.

**``run_metadata.json`` is rewritten each process, but the superseded payload survives** in
``run_metadata_history.jsonl``. Exp3 overwrote in place, so a resume under changed knobs
restamped the whole arm -- earlier iterations included -- and the values those iterations really
ran under were simply gone.

Import order
------------
``trl`` is imported before torch. On the local Blackwell card (sm_120) the other order segfaults
at CUDA init with no traceback, so this module calls
:func:`core.runtime.assert_import_order` at import time to turn a silent exit 139 into a message.

Two name collisions, on purpose
-------------------------------
:func:`build_grpo_config` and :func:`write_run_metadata` share their names with functions in
``core.config`` that do different jobs (``core.config`` builds the frozen CONFIG BUNDLE from
cell-1 globals and serialises a prepared payload; these build a ``trl.GRPOConfig`` and compose
that payload). The names are fixed by the module contract. **Do not star-import both modules into
one notebook namespace** -- import this module qualified (``from grpo import grpo_trainer``) or
use the unambiguous aliases :func:`build_trl_grpo_config` / :func:`write_arm_metadata`.
"""

from __future__ import annotations

import dataclasses
import gc
import json
import math
import os
import random
import time
from collections import defaultdict
from typing import Any, Callable, Dict, List, Mapping, Optional, Sequence, Tuple

# The import-order guard runs BEFORE trl/torch enter this process's module table, so it can still
# report the healthy state. It inspects sys.modules only and imports nothing heavy itself.
from core.runtime import assert_import_order

assert_import_order()

# trl FIRST -- see the module docstring. Everything below it pulls torch in transitively.
from trl import GRPOConfig, GRPOTrainer  # noqa: E402  (must precede torch on local sm_120)

# datasets SECOND, still ahead of torch: pyarrow and torch each initialise native
# runtimes and whichever goes first wins. MEASURED locally -- `import torch, datasets`
# is an access violation (exit 139) inside pyarrow.dataset. This module used to be safe
# only because core.* pulled pandas in first; that was luck, so it is now explicit.
from datasets import Dataset  # noqa: E402

import torch  # noqa: E402
from transformers import TrainerCallback  # noqa: E402

from core.config import (  # noqa: E402
    GenConfig,
    GRPOTrainingConfig,
    RolesConfig,
    RunPaths,
    config_to_metadata,
)
from core.config import write_run_metadata as _write_metadata_payload  # noqa: E402
from core.concurrency import AsyncPrimitives  # noqa: E402
from core.conversations import (  # noqa: E402
    extract_prompts_from_conversations,
    generate_all_conversations,
    load_conversations_dir,
)
from core.lookahead import LookaheadState  # noqa: E402
from core.policy import (  # noqa: E402
    attach_lora,
    list_hf_checkpoints,
    list_iteration_checkpoints,
    patch_generate,
    therapist_stop_token_ids,
    validate_iteration_checkpoint,
)
from core.recorder import EDARecorder, to_jsonable  # noqa: E402
from core.reward import make_reward_fn  # noqa: E402
from core.tb import patch_trainer_tensorboard_callback, setup_tensorboard_logging  # noqa: E402
from core.timing import log_session, metadata_fields  # noqa: E402
from roles import reset_client_cache  # noqa: E402
from tools.vllm_serve import ensure_alive  # noqa: E402

__all__ = [
    "EDA_SNAPSHOT_FILENAME",
    "EXPERIMENT_METADATA_FILENAME",
    "TB_SUBDIR",
    "DATASET_COLUMNS",
    "CheckpointMetadataCallback",
    "select_persona_ids",
    "ensure_servers_alive",
    "ensure_peft_policy",
    "run_generation_phase",
    "extract_training_prompts",
    "build_dataset",
    "build_grpo_config",
    "build_trl_grpo_config",
    "run_training_phase",
    "save_iteration_checkpoint",
    "push_adapter_to_hub",
    "write_run_metadata",
    "write_arm_metadata",
    "run_one_iteration",
    "run_final_eval",
]


# ==============================================================================
#  Constants
# ==============================================================================

#: The recorder buffer snapshotted INTO each HF checkpoint dir. Not one of
#: ``core.policy.HF_TRAINER_FILES``, so a checkpoint missing it still resumes -- it is extra
#: payload that HF/TRL ignore, and its absence costs EDA rows, never the iteration.
EDA_SNAPSHOT_FILENAME = "eda_snapshot.jsonl"

#: Per-checkpoint provenance written by :class:`CheckpointMetadataCallback`. Same "extra payload"
#: status as the snapshot above.
EXPERIMENT_METADATA_FILENAME = "experiment_metadata.json"

#: TensorBoard event files live under ``iteration_N/training/tb_logs``. Explicit, because HF's
#: ``default_logdir()`` builds a name from the clock and the hostname that is not a legal Windows
#: path segment -- and the run tree is written on Colab and read on Windows through Drive.
TB_SUBDIR = "tb_logs"

#: Columns every training sample carries into the HF dataset.
#:
#: WARNING: only ``prompt`` is TRL's. The other four reach the reward function as ``**kwargs``,
#: and ONLY because ``remove_unused_columns=False`` -- ``transcript`` is what the oracle grades,
#: ``patient_system_prompt`` is what look-ahead rolls out against, and ``persona_id`` /
#: ``conversation_id`` are what the EDA joins on. Dropping any of them does not raise at config
#: time; it raises inside the first reward call, an hour of generation later.
DATASET_COLUMNS = (
    "prompt",
    "transcript",
    "conversation_id",
    "persona_id",
    "patient_system_prompt",
)

#: GRPOConfig fields whose absence changes what is being trained rather than how it is reported.
#: If a future TRL renames one of these, :func:`build_grpo_config` raises instead of dropping it.
_CRITICAL_GRPO_FIELDS = (
    "num_generations",
    "num_iterations",
    "remove_unused_columns",
    "generation_kwargs",
    "scale_rewards",
    "beta",
    "temperature",
    "loss_type",
    "max_completion_length",
    "per_device_train_batch_size",
    "gradient_accumulation_steps",
)

_LOG = "  "


def _warn(message: str) -> None:
    """One-line warning channel. Printed, not ``warnings.warn``: a notebook shows print output
    inline and swallows warnings into a filter nobody set."""
    print(f"{_LOG}WARNING: {message}")


def _write_json_atomic(path: str, payload: Mapping[str, Any]) -> str:
    """Write JSON via a temp file plus ``os.replace``.

    A crash mid-write must never leave an unparseable ``iteration_metadata.json`` behind: the
    file sits next to an adapter that reads as a completed iteration, and a reader that fails on
    it cannot tell "torn write" from "this arm was never configured".
    """
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        json.dump(to_jsonable(dict(payload)), fh, indent=2, allow_nan=False)
    os.replace(tmp, path)
    return path


# ==============================================================================
#  Checkpoint callback
# ==============================================================================


class CheckpointMetadataCallback(TrainerCallback):
    """On every checkpoint save: write provenance, and snapshot the EDA buffer beside it.

    Args:
        iteration: the iteration being trained, stamped into the provenance file.
        metadata: the iteration's base metadata dict (arm name, rubric, K, MCL, ...). Copied
            into every checkpoint so a checkpoint dug out of Drive months later is
            self-describing.
        recorder: the iteration's :class:`~core.recorder.EDARecorder`, or ``None``.

    Notes:
        **The snapshot is the reason this callback exists.** HuggingFace resumes an interrupted
        run by fast-forwarding through the batches it already consumed, and a fast-forwarded
        batch never re-invokes the reward function -- so the branch records those steps produced
        are gone unless they were written down. Snapshotting INTO the checkpoint dir binds the
        snapshot to the exact checkpoint
        :func:`core.policy.get_latest_valid_hf_checkpoint` will walk back to, so the reload in
        :func:`run_one_iteration` can never restore rows from a checkpoint that was not the one
        resumed from.

        Both files are extra payload inside ``checkpoint-N/`` and are absent from
        ``core.policy.HF_TRAINER_FILES``, so writing them cannot make a checkpoint look valid,
        and failing to write them cannot make one look corrupt.

        Every failure here is swallowed after a warning. Telemetry must never be able to abort an
        optimizer step that cost GPU-hours to reach.
    """

    def __init__(self, *, iteration: int, metadata: Mapping[str, Any], recorder=None) -> None:
        self.iteration = int(iteration)
        self.metadata = dict(metadata or {})
        self.recorder = recorder

    def on_save(self, args, state, control, **kwargs):  # noqa: D102 - TrainerCallback protocol
        checkpoint_dir = os.path.join(args.output_dir, f"checkpoint-{state.global_step}")
        if not os.path.isdir(checkpoint_dir):
            # HF names the directory from global_step; if it is not there yet this hook fired for
            # a save that did not land, and writing our sidecars would create a phantom dir.
            return control
        try:
            _write_json_atomic(
                os.path.join(checkpoint_dir, EXPERIMENT_METADATA_FILENAME),
                {
                    **self.metadata,
                    "iteration": self.iteration,
                    "global_step": int(state.global_step),
                    "epoch": (None if state.epoch is None else float(state.epoch)),
                    "written_at": time.strftime("%Y-%m-%dT%H:%M:%S", time.localtime()),
                },
            )
        except Exception as exc:  # noqa: BLE001 - provenance must not fail a run
            _warn(f"could not write {EXPERIMENT_METADATA_FILENAME} ({exc})")

        if self.recorder is not None and getattr(self.recorder, "enabled", False):
            try:
                self.recorder.snapshot_to(os.path.join(checkpoint_dir, EDA_SNAPSHOT_FILENAME))
            except Exception as exc:  # noqa: BLE001
                _warn(f"could not snapshot the EDA buffer ({exc})")
        return control


# ==============================================================================
#  Personas + servers
# ==============================================================================


def select_persona_ids(n_personas: int, count: int, *, seed: int, iteration: int) -> List[int]:
    """Which personas this iteration runs, and in what order.

    Args:
        n_personas: size of the full permutation set (96 for the V3 patients).
        count: how many to run this iteration (``NUM_CONVERSATIONS_PER_ITER``).
        seed: the run seed.
        iteration: 1-based loop counter. The final generate-only pass uses
            ``num_iterations + 1``, matching Exp3's convention.

    Returns:
        ``count`` STABLE persona ids (0-based indices into ``generate_all_permutations()``
        order), shuffled by ``Random(seed + iteration)``.

    Notes:
        The shuffle decides WHICH personas run and in what order they are processed. It never
        reaches a filename: ``core.conversations`` names every conversation ``pers<PID>.csv`` by
        the stable persona id, so ``pers07.csv`` is persona 7 in every iteration of every arm
        (Exp3 fix #2). If you came from Exp3, this is the thing that changed -- there is nothing
        to replay, and pairing across iterations is a join on ``persona_id``.

        When ``count >= n_personas`` every persona runs and the shuffle only reorders the
        processing, which still matters: it decides which personas share a generation batch.
    """
    if n_personas <= 0:
        raise ValueError("select_persona_ids: the permutation set is empty")
    ids = list(range(int(n_personas)))
    random.Random(int(seed) + int(iteration)).shuffle(ids)
    return ids[: max(0, int(count))]


def ensure_servers_alive(
    handles: Optional[Mapping[str, Any]],
    *,
    client_factory: Optional[Callable[[], Any]] = None,
    phase: str = "",
) -> Optional[Any]:
    """Probe every vLLM server at a phase boundary; relaunch any that stopped answering.

    Args:
        handles: the ``{model: ServerHandle}`` dict ``tools.vllm_serve.serve_roles`` returned.
            ``None`` or empty is a no-op -- an arm whose roles are all vendor APIs has no
            process to watch.
        client_factory: builds a fresh async client. Called only when a server was actually
            restarted.
        phase: label for the log line (``"generate"``, ``"train"``, ...).

    Returns:
        A fresh client when a restart happened AND *client_factory* was supplied; ``None``
        otherwise. ``None`` means "keep using the client you have".

    Raises:
        RuntimeError: from :func:`tools.vllm_serve.ensure_alive` when a handle exhausts its
            restart budget. A server that keeps dying is a configuration problem -- almost
            always ``gpu_memory_utilization`` colliding with the trainer's peak -- and it should
            stop the run rather than present itself as a mysterious slowdown.

    Notes:
        **A restart invalidates every cached client.** ``roles.make_client`` caches by binding,
        and the cached client holds a connection pool to a process that no longer exists; the
        symptom is a burst of connection errors on the next phase, blamed on the wrong thing.
        This calls ``roles.reset_client_cache()`` after any restart. If no *client_factory* was
        given the caller is still holding the stale object, so that case warns loudly instead of
        pretending it recovered.
    """
    if not handles:
        return None
    restarted = 0
    for handle in list(handles.values()):
        before = int(getattr(handle, "restarts", 0))
        ensure_alive(handle)
        if int(getattr(handle, "restarts", 0)) > before:
            restarted += 1
    if not restarted:
        return None

    dropped = reset_client_cache()
    label = f" before {phase}" if phase else ""
    print(f"{_LOG}vLLM: {restarted} server(s) restarted{label}; dropped {dropped} cached client(s)")
    if client_factory is None:
        _warn(
            "a vLLM server was restarted but no client_factory was given -- the client still in "
            "use holds a connection pool to the dead process. Rebuild it with "
            "roles.make_client(binding) before the next phase."
        )
        return None
    return client_factory()


def ensure_peft_policy(policy, cfg: GRPOTrainingConfig, tokenizer):
    """Return *policy* with a trainable LoRA adapter attached, wrapping it if it has none.

    Args:
        policy: the therapist policy -- a bare base model on a fresh iteration 1, or the
            ``PeftModel`` ``core.policy.resolve_start_state`` handed back on a resume.
        cfg: supplies ``lora_r`` / ``lora_alpha`` / ``lora_dropout`` / ``lora_target_modules``.
        tokenizer: re-bound into ``generate`` by :func:`core.policy.patch_generate`.

    Returns:
        A PEFT-wrapped policy (the same object when it already was one).

    Notes:
        **Why the adapter is attached here and not by ``GRPOTrainer(peft_config=...)``.** The
        reward closure captures this object so that K-turn look-ahead rolls out under the weights
        being trained. Let the trainer do the wrapping and the closure holds the *unwrapped base*
        instead: every simulated therapist turn of that iteration comes from a policy with no
        adapter. Nothing raises, and at step 0 nothing even differs -- a freshly-initialised LoRA
        is numerically identity -- so the divergence grows silently through the iteration. TRL is
        therefore always handed ``peft_config=None`` (see :func:`run_training_phase`); the two
        choices are mutually exclusive and this is the one Exp4 makes.

        **Call it AFTER the generation phase.** Iteration 1 must generate ``model_iter_0`` with
        the genuinely untrained base policy; attaching first would be numerically identical but
        would make the "base" folder a claim rather than a fact.
    """
    if hasattr(policy, "peft_config"):
        patch_generate(policy, tokenizer)
        return policy
    wrapped = attach_lora(
        policy,
        r=cfg.lora_r,
        alpha=cfg.lora_alpha,
        dropout=cfg.lora_dropout,
        target_modules=cfg.lora_target_modules,
    )
    patch_generate(wrapped, tokenizer)
    return wrapped


# ==============================================================================
#  Phase 1: generation
# ==============================================================================


def run_generation_phase(
    *,
    policy,
    tokenizer,
    client,
    roles: RolesConfig,
    gen: GenConfig,
    primitives: AsyncPrimitives,
    permutations: Sequence[Dict[str, str]],
    therapist_system_prompt: str,
    therapist_init_utterance: str,
    conv_dir: str,
    persona_ids: Sequence[int],
    patient_seed: Optional[int] = None,
    label: str = "",
) -> Tuple[List[Any], float]:
    """Simulate this iteration's conversations and write them to *conv_dir*.

    Args:
        policy: the CURRENT therapist policy. Switched to ``eval()`` with ``use_cache=True`` here
            and left that way -- :func:`run_training_phase` switches it back, so a caller that
            generates without training must do so itself.
        client: async client for the patient role.
        roles: supplies ``roles.patient`` (model, per-attempt timeout, retries, extra_body).
        gen: conversation-shaping knobs (length, temperatures, batch size, stop strings).
        primitives: the shared loop-keyed semaphores and GPU lock.
        permutations: the FULL ``generate_all_permutations()`` list in canonical order. It is
            indexed by persona id, so a shuffled subset here would silently pair each
            conversation with the wrong patient.
        conv_dir: ``conversations/<ARM>/model_iter_<N>``. Conversations already on disk there are
            reloaded, not regenerated, which is what makes a killed generation phase cheap to
            resume.
        persona_ids: which personas to run, in processing order (see :func:`select_persona_ids`).
        patient_seed: forwarded to the patient API when the backend honours it.
        label: printed in the phase banner.

    Returns:
        ``(states, seconds)`` -- the usable conversations, sorted by persona id, and the
        wall-clock this process spent here. The seconds go straight into
        ``core.timing.log_session``; they are per-process by construction, which is correct,
        because the session log sums across processes rather than trusting any one of them.

    Notes:
        ``batch_size`` is a SAFETY setting on the local 12 GB card, not a throughput knob:
        weights plus roughly 1.1 GB per concurrent conversation, and an over-budget VRAM request
        there reboots the machine instead of raising. On the A100 a large batch is what amortises
        the patient round-trip across the whole batch.
    """
    start = time.time()
    banner = f" ({label})" if label else ""
    print(f"\n{_LOG}-- Generation{banner}: {len(persona_ids)} conversations -> {conv_dir}")

    policy.eval()
    policy.config.use_cache = True

    states = generate_all_conversations(
        policy,
        tokenizer,
        client,
        roles.patient,
        primitives,
        permutations,
        therapist_system_prompt,
        therapist_init_utterance,
        persona_ids=list(persona_ids),
        save_dir=conv_dir,
        num_utterances=gen.num_utterances_for_data,
        max_tokens=gen.max_tokens_per_response,
        temperature_therapist=gen.temperature_therapist,
        temperature_patient=gen.temperature_patient,
        therapist_max_input_tokens=gen.therapist_max_input_tokens,
        # [] = no string stopping (Instruct arms); None would fall back to the ChatML defaults.
        stop_strings=list(gen.stop_strings),
        patient_seed=patient_seed,
        batch_size=gen.conversation_batch_size,
        max_retries_without_progress=gen.max_retries_without_progress,
        verbose=gen.verbose,
        verbose_detailed=gen.verbose_detailed,
    )

    seconds = time.time() - start
    avg_len = (sum(s.n_utterances for s in states) / len(states)) if states else 0.0
    print(
        f"{_LOG}Generated {len(states)}/{len(persona_ids)} conversations in {seconds:.1f}s "
        f"(avg {avg_len:.1f} utterances)"
    )
    return states, seconds


# ==============================================================================
#  Phase 2: prompt extraction + datasets
# ==============================================================================


def extract_training_prompts(
    states: Sequence[Any],
    *,
    tokenizer,
    gen: GenConfig,
    therapist_system_prompt: str,
    permutations: Sequence[Dict[str, str]],
) -> List[Dict[str, Any]]:
    """Slice finished conversations into per-turn training samples under the MCL filter.

    Args:
        states: the conversations from :func:`run_generation_phase`.
        gen: supplies ``min_conv_length`` (MCL) and ``max_prompt_tokens``.
        permutations: the FULL permutation list, indexed by persona id -- it is where each
            sample's ``patient_system_prompt`` comes from.

    Returns:
        One dict per eligible slice, carrying :data:`DATASET_COLUMNS`.

    Notes:
        MCL is the response to the reward-faithfulness finding: a partial cut is what the
        training reward grades, while the experiment evaluates whole conversations, and pairwise
        rank agreement between the two is barely above chance at 2 utterances and only clears 0.8
        near 10. A slice shorter than MCL is dropped rather than down-weighted.
    """
    samples = extract_prompts_from_conversations(
        states,
        therapist_system_prompt,
        tokenizer,
        min_conv_length=gen.min_conv_length,
        max_prompt_tokens=gen.max_prompt_tokens,
        permutations=permutations,
    )
    print(
        f"{_LOG}Extracted {len(samples)} training prompts from {len(states)} conversations "
        f"(MCL={gen.min_conv_length}, max_prompt_tokens={gen.max_prompt_tokens})"
    )
    return samples


def _to_dataset(samples: Sequence[Mapping[str, Any]]) -> Dataset:
    """Build an HF ``Dataset`` carrying exactly :data:`DATASET_COLUMNS`."""
    missing = [c for c in DATASET_COLUMNS if samples and c not in samples[0]]
    if missing:
        raise ValueError(
            f"training samples are missing {missing}; every one of {list(DATASET_COLUMNS)} is "
            f"needed downstream (transcript -> the oracle, patient_system_prompt -> look-ahead, "
            f"persona_id/conversation_id -> the EDA join). "
            f"core.conversations.extract_prompts_from_conversations produces all five."
        )
    return Dataset.from_dict({c: [s[c] for s in samples] for c in DATASET_COLUMNS})


def build_dataset(
    samples: Sequence[Mapping[str, Any]],
    *,
    eval_split_ratio: float,
    seed: int,
    verbose: bool = True,
) -> Tuple[Dataset, Optional[Dataset]]:
    """Split per-turn samples into train/eval HuggingFace datasets, grouped by CONVERSATION.

    Args:
        samples: what :func:`extract_training_prompts` returned.
        eval_split_ratio: fraction of CONVERSATIONS (not samples) held out.
        seed: shuffles the conversation ids. Fixed across iterations on purpose -- the personas
            themselves are already reshuffled per iteration, and re-seeding here as well would
            make the eval split move for two independent reasons.
        verbose: print the split summary.

    Returns:
        ``(train_dataset, eval_dataset)``. ``eval_dataset`` is ``None`` when the split is empty
        (``eval_split_ratio`` of 0, or a single conversation), which
        :func:`build_grpo_config` reads as "run no evaluation".

    Raises:
        ValueError: no samples at all, or a sample missing a required column. An empty prompt set
            means the conversations are shorter than MCL or the generation phase produced
            nothing; training on zero rows would otherwise succeed and write an adapter that
            learned nothing.

    Notes:
        **The split is at CONVERSATION level, never sample level.** Every slice of one
        conversation shares its opening turns, so a sample-level split puts near-identical
        contexts on both sides and the eval reward becomes a measurement of memorisation. The
        overlap is asserted, not assumed.

        Eval is not free here: with ``eval_strategy="epoch"`` TRL samples ``G`` completions for
        every eval prompt and the reward function grades all of them, so the held-out fraction is
        also a fraction of the oracle bill (which, on the open stack, is GPU time rather than
        money -- but it is still time).
    """
    if not samples:
        raise ValueError(
            "build_dataset: no training prompts. Either the generation phase produced no usable "
            "conversations, or every conversation is shorter than MIN_CONV_LENGTH."
        )

    groups: Dict[Any, List[Mapping[str, Any]]] = defaultdict(list)
    for sample in samples:
        groups[sample["conversation_id"]].append(sample)

    conv_ids = sorted(groups)
    random.Random(int(seed)).shuffle(conv_ids)

    ratio = float(eval_split_ratio)
    n_eval = int(len(conv_ids) * ratio)
    if ratio > 0.0:
        n_eval = max(1, n_eval)
    # Train must never be empty; with one conversation there is nothing to hold out.
    n_eval = max(0, min(n_eval, len(conv_ids) - 1))

    eval_ids = set(conv_ids[:n_eval])
    train_ids = set(conv_ids[n_eval:])
    overlap = train_ids & eval_ids
    if overlap:
        raise ValueError(f"build_dataset: train/eval conversation overlap {sorted(overlap)}")

    train_samples = [s for cid in sorted(train_ids) for s in groups[cid]]
    eval_samples = [s for cid in sorted(eval_ids) for s in groups[cid]]

    n_missing_patient = sum(1 for s in samples if not s.get("patient_system_prompt"))
    if n_missing_patient:
        _warn(
            f"{n_missing_patient}/{len(samples)} samples carry an EMPTY patient_system_prompt. "
            f"At K>0 look-ahead would roll out against a default patient instead of the one the "
            f"conversation was generated with, silently changing what the reward measures."
        )

    train_dataset = _to_dataset(train_samples)
    eval_dataset = _to_dataset(eval_samples) if eval_samples else None

    if verbose:
        print(
            f"{_LOG}Split: {len(train_ids)} train / {len(eval_ids)} eval conversations "
            f"(grouped, 0 overlap) -> {len(train_dataset)} / "
            f"{len(eval_dataset) if eval_dataset is not None else 0} prompts"
        )
    return train_dataset, eval_dataset


# ==============================================================================
#  Phase 3: the TRL config
# ==============================================================================


def _grpo_config_fields() -> frozenset:
    return frozenset(f.name for f in dataclasses.fields(GRPOConfig))


def build_grpo_config(
    cfg: GRPOTrainingConfig,
    gen: GenConfig,
    *,
    output_dir: str,
    num_train_prompts: int,
    has_eval: bool = True,
    tb_log_dir: Optional[str] = None,
    tokenizer=None,
) -> GRPOConfig:
    """Assemble the ``trl.GRPOConfig`` for one iteration.

    Args:
        cfg: the frozen training config (batch arithmetic, GRPO knobs, checkpointing).
        gen: supplies the stop strings TRL must sample against.
        output_dir: ``iteration_N/training`` -- the HF Trainer output dir, where
            ``checkpoint-*`` and ``tb_logs/`` land.
        num_train_prompts: length of the train dataset, used only to size the LR warmup.
        has_eval: False disables evaluation entirely (an empty held-out split).
        tb_log_dir: TensorBoard directory; defaults to ``<output_dir>/tb_logs``.
        tokenizer: the therapist tokenizer. Required when ``gen.stop_strings`` is empty (an
            Instruct-therapist arm): TRL's in-loop sampling then stops on the
            ``therapist_stop_token_ids`` eos list passed through ``generation_kwargs``
            instead of on stop strings.

    Returns:
        A ``GRPOConfig``.

    Raises:
        RuntimeError: the pinned TRL does not accept one of :data:`_CRITICAL_GRPO_FIELDS`. A
            renamed cosmetic field is dropped with a warning; a renamed critical one would
            change what is trained while looking like it worked, so it stops the run.

    Notes:
        **``per_device_train_batch_size`` counts COMPLETIONS, not prompts.** TRL's
        ``RepeatSampler`` emits ``num_generations`` completions per prompt, so the unique prompts
        consumed per optimizer step are
        ``(per_device / num_generations) * gradient_accumulation_steps = (64/8) * 2 = 16`` --
        matched to PTO's 16 preference pairs per step so the two methods take
        comparable-sized steps. Read that number off ``cfg.prompts_per_step``.

        **Keep ``gradient_accumulation_steps=2`` for the prompts/step match, not for gradient
        scale.** On the pinned trl 1.4.0, ``gas`` changes are gradient-scale-NEUTRAL: trl
        bypasses transformers' own ``training_step`` scaling by passing a non-None
        ``compute_loss_func`` sentinel (installed trl ``grpo_trainer.py`` ~:652-657) and divides
        the loss exactly once by ``current_gradient_accumulation_steps`` (~:2351-2352). The old
        "net scale is 1/gas^2, halving gas doubles the gradient" story was measured on Exp3's
        earlier stack and is FALSE here -- re-verify those two line references on any trl bump.
        What ``gas=2`` still buys is the design match: 128 completions -> 16 unique prompts per
        optimizer step, mirrored to PTO's 16 pairs.

        **And a bigger batch buys nothing.** TRL already issues ONE ``generate()`` per optimizer
        step over the whole ``generation_batch_size`` (``per_device x gas``), so ``64 x 2`` and
        ``128 x 1`` emit the same single call. There is no throughput on the table here.

        **``generation_kwargs`` carries the stop mechanism and is not optional.** On a
        BASE-therapist arm it is ``{"stop_strings": ...}``: ``<|im_end|>`` is template text,
        not the base tokenizer's EOS, so without it the 1B policy samples straight through the
        marker to ``max_completion_length`` and writes the patient's reply itself -- polluting
        the transcript the oracle grades AND, because GRPO credits every sampled token, training
        the policy toward 200-token rambles. ``core.policy.patch_generate`` is what makes
        ``stop_strings`` take effect at all -- HuggingFace ignores it silently unless a
        tokenizer is passed to the same call, and TRL does not pass one. On an
        INSTRUCT-therapist arm (empty ``gen.stop_strings``) it is
        ``{"eos_token_id": therapist_stop_token_ids(tokenizer)}`` instead: the Llama-3 turn
        markers are single special tokens there, so token-id stopping is exact and skips the
        per-call stop-string criteria build.

        **``remove_unused_columns=False`` is required.** Without it TRL strips ``transcript``,
        ``persona_id`` and ``patient_system_prompt`` and the reward function cannot grade or look
        ahead; see :data:`DATASET_COLUMNS`.

        The warmup is computed from the real prompts-per-step. Getting it wrong only mis-sizes
        the warmup itself -- the HF Trainer recomputes the cosine horizon from the actual
        dataloader length -- but Exp3 printed a figure ``num_generations`` too small, which read
        like a broken schedule for a year.
    """
    prompts_per_step = max(1, int(cfg.prompts_per_step))
    steps_per_epoch = max(1, math.ceil(max(1, int(num_train_prompts)) / prompts_per_step))
    total_steps = max(1, steps_per_epoch * int(cfg.epochs_per_iteration))
    warmup_steps = max(0, math.ceil(total_steps * float(cfg.warmup_steps_ratio)))

    if num_train_prompts < prompts_per_step:
        _warn(
            f"only {num_train_prompts} train prompts for {prompts_per_step} prompts/step -- this "
            f"iteration takes a single, padded optimizer step per epoch."
        )

    log_dir = tb_log_dir or os.path.join(output_dir, TB_SUBDIR)
    os.makedirs(log_dir, exist_ok=True)

    print(
        f"{_LOG}GRPO batch: per_device {cfg.train_batch_size} completions x gas "
        f"{cfg.gradient_accumulation_steps} = {cfg.generation_batch_size} completions -> "
        f"{prompts_per_step} prompts/step (G={cfg.num_generations})"
    )
    print(
        f"{_LOG}Schedule: {steps_per_epoch} steps/epoch x {cfg.epochs_per_iteration} epochs = "
        f"{total_steps} steps, warmup {warmup_steps} (ratio {cfg.warmup_steps_ratio})"
    )

    kwargs: Dict[str, Any] = {
        "output_dir": output_dir,
        "run_name": cfg.adapter_repo or cfg.experiment_name,
        "hub_model_id": cfg.adapter_repo or None,
        "push_to_hub": False,  # pushing is done explicitly, per iteration, in push_adapter_to_hub
        # -- batch arithmetic (see the Notes: completions, not prompts; never collapse gas) --
        "per_device_train_batch_size": cfg.train_batch_size,
        "per_device_eval_batch_size": cfg.eval_batch_size,
        "gradient_accumulation_steps": cfg.gradient_accumulation_steps,
        "num_train_epochs": cfg.epochs_per_iteration,
        # -- GRPO proper --
        "num_generations": cfg.num_generations,
        "num_iterations": cfg.grpo_inner_iterations,  # inner PPO iterations (mu), NOT the arm loop
        "beta": cfg.grpo_beta,                        # KL against the iteration-start reference
        "temperature": cfg.grpo_temperature,
        "loss_type": cfg.grpo_loss_type,
        "scale_rewards": "group",                     # A = (r - mean_g) / std_g over the G siblings
        "max_completion_length": cfg.max_completion_length,
        # Without this the base policy self-plays the patient to the token cap (see the Notes).
        # Base-therapist arms stop on the ChatML strings; Instruct arms have EMPTY stop_strings
        # and stop on the eos-id list instead -- <|eot_id|>/<|eom_id|>/<|start_header_id|> are
        # single special tokens there, so token-id stopping is exact and costs nothing per call.
        "generation_kwargs": (
            {"stop_strings": list(gen.stop_strings)} if gen.stop_strings
            else ({"eos_token_id": therapist_stop_token_ids(tokenizer)}
                  if tokenizer is not None else None)
        ),
        # Required: TRL would otherwise strip every column the reward fn reads.
        "remove_unused_columns": False,
        # -- optimizer --
        "learning_rate": cfg.learning_rate,
        "lr_scheduler_type": "cosine",
        "warmup_steps": warmup_steps,
        "gradient_checkpointing": cfg.gradient_checkpointing,
        "bf16": True,
        "seed": cfg.seed,
        # -- checkpointing / logging --
        "logging_steps": cfg.logging_steps,
        "save_strategy": cfg.save_strategy,
        "save_steps": cfg.save_steps,
        "save_total_limit": cfg.save_total_limit,
        "report_to": list(cfg.report_to),
        "log_completions": cfg.log_completions,
        "eval_strategy": "epoch" if has_eval else "no",
    }
    if cfg.gradient_checkpointing:
        # Re-entrant checkpointing does not compose with PEFT's frozen base parameters.
        kwargs["gradient_checkpointing_kwargs"] = {"use_reentrant": False}

    known = _grpo_config_fields()
    unknown = sorted(k for k in kwargs if k not in known)
    critical_missing = [k for k in unknown if k in _CRITICAL_GRPO_FIELDS]
    if critical_missing:
        raise RuntimeError(
            f"the installed trl does not accept {critical_missing} on GRPOConfig. These decide "
            f"WHAT is trained (group size, KL, reward scaling, the column passthrough), so they "
            f"cannot be dropped silently -- a run without them would look successful and train "
            f"something else. Pin trl to the version in requirements.txt, or port this config "
            f"site to the new field names."
        )
    for name in unknown:
        _warn(f"GRPOConfig has no field {name!r} in the installed trl; dropping it")
        kwargs.pop(name, None)

    return GRPOConfig(**kwargs)


#: Unambiguous alias. ``core.config.build_grpo_config`` builds the frozen CONFIG BUNDLE from
#: cell-1 globals; this one builds TRL's trainer arguments. Use this name when both modules are
#: imported into one namespace.
build_trl_grpo_config = build_grpo_config


# ==============================================================================
#  Phase 3: training
# ==============================================================================


def run_training_phase(
    *,
    policy,
    tokenizer,
    grpo_args: GRPOConfig,
    reward_funcs,
    train_dataset: Dataset,
    eval_dataset: Optional[Dataset],
    iteration: int,
    iter_metadata: Optional[Mapping[str, Any]] = None,
    recorder: Optional[EDARecorder] = None,
    resume_checkpoint: Optional[str] = None,
    tb_log_dir: Optional[str] = None,
) -> Tuple[Any, int, float]:
    """Build a ``GRPOTrainer``, train it, and hand the trainer back.

    Args:
        policy: the PEFT-wrapped policy from :func:`ensure_peft_policy`. It is the SAME object
            the reward closure captured, which is what makes look-ahead roll out under the
            weights being trained.
        grpo_args: from :func:`build_grpo_config`.
        reward_funcs: the async callable from ``core.reward.make_reward_fn``.
        eval_dataset: ``None`` disables evaluation; ``grpo_args.eval_strategy`` must already
            agree.
        iter_metadata: copied into every checkpoint by :class:`CheckpointMetadataCallback`.
        recorder: snapshotted into every checkpoint by the same callback.
        resume_checkpoint: an HF ``checkpoint-*`` path, or ``None``. Applies to THIS call only --
            the caller must not pass it again for the next iteration.
        tb_log_dir: defaults to ``<output_dir>/tb_logs``.

    Returns:
        ``(trainer, step_delta, seconds)``. ``step_delta`` counts only steps executed in THIS
        call: on a resume, ``trainer.state.global_step`` includes the fast-forwarded ones, and
        adding those to the cumulative offset again would double-count the TensorBoard x-axis.

    Notes:
        **``peft_config`` is always ``None``.** The adapter is attached before the trainer exists
        (see :func:`ensure_peft_policy`); handing TRL a config as well would wrap an already
        wrapped model, and the nested ``adapter_config.json`` no longer describes the model you
        think it does.

        **The TensorBoard directory is set BEFORE the trainer is constructed.**
        ``TensorBoardCallback.__init__`` reads its environment variable once and keeps the value,
        and HF's fallback ``default_logdir()`` builds a clock-and-hostname name that is not a
        legal Windows path segment -- Exp3 collected ``WinError 123`` from it. The
        post-construction patch re-points a callback that was built anyway (a resumed iteration
        can reuse one whose directory was captured from a previous environment).

        **``patch_generate`` runs on both sides of ``train()``.** The trainer hands back a fresh
        ``generate`` when it builds its wrapper, and ``train()`` may rebuild it again; an
        unpatched ``generate`` ignores ``stop_strings`` silently and the anti-degeneracy stack
        loses its first line of defence.

        The policy is put in ``train()`` with ``config.use_cache = False`` -- the training
        setting, and what gradient checkpointing requires. TRL's own sampling passes an explicit
        ``generation_config`` whose ``use_cache`` is True, so in-loop generation still uses the
        KV cache; the look-ahead rollout toggles ``eval()`` + ``use_cache`` itself and restores
        both in a ``finally``, because it runs mid-optimizer-step.

        Each iteration builds a FRESH trainer, so the Adam moments reset every iteration while
        the LoRA weights carry over -- a warm restart per iteration. That is deliberate and is
        matched on the PTO side; it is not an artefact of the loop structure.
    """
    start = time.time()
    log_dir = tb_log_dir or os.path.join(grpo_args.output_dir, TB_SUBDIR)
    report_to = [str(t) for t in (getattr(grpo_args, "report_to", None) or [])]

    policy.config.use_cache = False
    policy.train()

    # Must precede the Trainer: the callback reads the env var in __init__ and keeps it.
    setup_tensorboard_logging(log_dir)

    trainer = GRPOTrainer(
        model=policy,
        args=grpo_args,
        processing_class=tokenizer,
        reward_funcs=reward_funcs,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
        peft_config=None,  # the adapter is already attached -- see ensure_peft_policy
        callbacks=[
            CheckpointMetadataCallback(
                iteration=iteration, metadata=iter_metadata or {}, recorder=recorder
            )
        ],
    )

    if "tensorboard" in report_to:
        patch_trainer_tensorboard_callback(trainer, log_dir)

    patch_generate(trainer.model, tokenizer)

    resumed_steps = 0
    if resume_checkpoint:
        try:
            resumed_steps = int(os.path.basename(resume_checkpoint).split("-")[-1])
        except ValueError:
            resumed_steps = 0
        print(f"{_LOG}Resuming from {os.path.basename(resume_checkpoint)} ({resumed_steps} steps)")

    trainer.train(resume_from_checkpoint=resume_checkpoint or None)

    patch_generate(trainer.model, tokenizer)

    step_delta = max(0, int(trainer.state.global_step) - resumed_steps)
    seconds = time.time() - start
    print(f"{_LOG}Training complete in {seconds:.1f}s ({step_delta} new optimizer steps)")
    return trainer, step_delta, seconds


# ==============================================================================
#  Phase 4: saving
# ==============================================================================


def save_iteration_checkpoint(
    *,
    policy,
    tokenizer,
    paths: RunPaths,
    iteration: int,
    metadata: Mapping[str, Any],
) -> str:
    """Write ``iteration_metadata.json``, then the adapter. Returns the adapter directory.

    Args:
        policy: the trained policy (``trainer.model``).
        tokenizer: saved beside the adapter so the checkpoint carries its own ChatML template.
        paths: the run's :class:`~core.config.RunPaths`.
        iteration: which iteration is being closed out.
        metadata: the iteration record -- counts, timings, arm identity.

    Returns:
        ``iteration_N/adapter``.

    Notes:
        **Order matters: metadata first, adapter last.** The adapter directory's existence is the
        ONLY definition of "this iteration is done" (``core.policy.list_iteration_checkpoints``,
        the resume logic, the EDA and the eval-generation tool all key on it). Writing the
        adapter first and dying before the metadata would leave an iteration that reads as
        complete with no record of what it cost or how it was configured; writing the metadata
        first and dying leaves an incomplete iteration with a stale sidecar, which the next
        resume simply overwrites.

        The epoch checkpoint list is captured from ``iteration_N/training`` before either write,
        so the record names the checkpoints ``save_total_limit`` actually left on disk.
    """
    iter_dir = paths.ensure_iteration_dir(iteration)
    training_dir = paths.training_dir(iteration)
    adapter_dir = paths.adapter_dir(iteration)

    checkpoints = [os.path.basename(c) for c in list_hf_checkpoints(training_dir)]
    payload = {**dict(metadata), "epoch_checkpoints": checkpoints}
    _write_json_atomic(paths.iteration_metadata_path(iteration), payload)

    os.makedirs(adapter_dir, exist_ok=True)
    policy.save_pretrained(adapter_dir)
    tokenizer.save_pretrained(adapter_dir)

    print(f"{_LOG}Saved adapter -> {adapter_dir}")
    print(f"{_LOG}Epoch checkpoints kept: {checkpoints or '(none)'}")
    print(f"{_LOG}Iteration metadata -> {os.path.join(iter_dir, 'iteration_metadata.json')}")
    return adapter_dir


def push_adapter_to_hub(
    policy,
    cfg: GRPOTrainingConfig,
    *,
    iteration: Optional[int] = None,
    commit_message: Optional[str] = None,
) -> bool:
    """Push the current adapter to the Hub, if this arm is configured to.

    Args:
        policy: the PEFT-wrapped policy.
        cfg: ``push_to_hub`` and ``hub_entity`` decide whether anything happens;
            ``cfg.adapter_repo`` is ``<hub_entity>/<EXPERIMENT_NAME>``.
        iteration: stamped into the default commit message.
        commit_message: overrides the default.

    Returns:
        True when a push succeeded, False when it was skipped or failed.

    Notes:
        **A failed push never aborts training.** It is a safety net on top of the local adapter,
        not the artifact itself: the local copy on Drive is what the next iteration resumes from
        and what the EDA reads. Losing a Colab session to a Hub 500 would be the expensive
        failure.
    """
    if not cfg.push_to_hub:
        return False
    repo = cfg.adapter_repo
    if not repo:
        _warn("push_to_hub is set but hub_entity is empty; there is nowhere to push")
        return False
    message = commit_message or (
        f"iteration_{iteration}/{cfg.num_iterations}" if iteration is not None else "adapter"
    )
    try:
        policy.push_to_hub(repo_id=repo, commit_message=message)
    except Exception as exc:  # noqa: BLE001 - the local adapter is the artifact
        _warn(f"Hub push to {repo} failed ({type(exc).__name__}: {exc}); the local adapter is intact")
        return False
    print(f"{_LOG}Pushed adapter -> {repo} ({message})")
    return True


def write_run_metadata(
    cfg: GRPOTrainingConfig,
    roles: RolesConfig,
    gen: GenConfig,
    oracle_cfg: Any,
    la_cfg: Any,
    paths: RunPaths,
    *,
    extra: Optional[Mapping[str, Any]] = None,
) -> str:
    """Write ``run_metadata.json`` and append this process's payload to the history log.

    Args:
        cfg, roles, gen, oracle_cfg, la_cfg, paths: the whole config bundle, in any order --
        ``core.config.config_to_metadata`` indexes them by type. Passing the COMPLETE bundle
        matters: the completeness assertion that guarantees every silently-mutable knob reached
        the payload only runs when all six sections are present.
        extra: anything runtime-only worth recording under a ``runtime`` key -- the host banner,
            the realized look-ahead sub-batch, the oracle-sanity report.

    Returns:
        The path of ``run_metadata.json``.

    Notes:
        This is a composition of ``core.config.config_to_metadata`` and
        ``core.config.write_run_metadata``, not a second implementation.

        **The history log is the point (Exp3 fix #5).** The current file is overwritten -- a
        reader wants exactly one "what is this arm configured as?" -- but every process appends
        its own line to ``run_metadata_history.jsonl`` first, so a resume under changed knobs
        leaves a trace instead of restamping the whole arm, earlier iterations included.

        Call it once per process, at the start. ``EXPERIMENT_NAME`` encodes only the arm's
        identity axes, so a changed learning rate, tau, temperature or sub-batch produces a
        byte-identical folder name and this file is the ONLY thing that can tell the two runs
        apart.
    """
    payload = config_to_metadata(cfg, roles, gen, oracle_cfg, la_cfg, paths)
    if extra:
        payload["runtime"] = to_jsonable(dict(extra))
    path = _write_metadata_payload(payload, paths)
    print(f"{_LOG}Run metadata -> {path}")
    return path


#: Unambiguous alias -- ``core.config.write_run_metadata`` takes an already-built payload, this
#: one takes the config bundle. Use this name when both are imported into one namespace.
write_arm_metadata = write_run_metadata


# ==============================================================================
#  One iteration
# ==============================================================================


def _iteration_metadata_base(
    *,
    cfg: GRPOTrainingConfig,
    gen: GenConfig,
    roles: RolesConfig,
    la_cfg: Any,
    iteration: int,
) -> Dict[str, Any]:
    """The identity fields every checkpoint and the iteration record both carry.

    Deliberately small: the arm name already encodes method, rubric, K, MCL, G and both role
    tags, and ``run_metadata.json`` carries every other knob. What is repeated here is what makes
    a checkpoint dug out of Drive months later self-describing without a second file.
    """
    return {
        "experiment_name": cfg.experiment_name,
        "method": cfg.method,
        "iteration": int(iteration),
        "base_model": cfg.base_model_id,
        "oracle_model": roles.oracle.model,
        "patient_model": roles.patient.model,
        "questionnaire_ids": list(cfg.questionnaire_ids),
        "lookahead_k": int(getattr(la_cfg, "k", 0)),
        "min_conv_length": gen.min_conv_length,
        "num_generations": cfg.num_generations,
        "prompts_per_step": cfg.prompts_per_step,
        "grpo_beta": cfg.grpo_beta,
        "learning_rate": cfg.learning_rate,
        "lora_r": cfg.lora_r,
    }


def run_one_iteration(
    *,
    iteration: int,
    policy,
    tokenizer,
    client,
    cfg: GRPOTrainingConfig,
    gen: GenConfig,
    roles: RolesConfig,
    oracle_cfg: Any,
    la_cfg: Any,
    paths: RunPaths,
    primitives: AsyncPrimitives,
    permutations: Sequence[Dict[str, str]],
    therapist_system_prompt: str,
    therapist_init_utterance: str,
    start_iteration: int = 1,
    resume_checkpoint: Optional[str] = None,
    cumulative_step_offset: int = 0,
    tb_logger=None,
    server_handles: Optional[Mapping[str, Any]] = None,
    client_factory: Optional[Callable[[], Any]] = None,
    skip_if_complete: bool = True,
) -> Dict[str, Any]:
    """Run one full iteration: generate -> extract -> split -> train -> save.

    Args:
        iteration: 1-based. Iteration ``n`` generates with the iter-(``n``-1) policy, writes
            ``model_iter_{n-1}``, and produces ``iteration_n/adapter/``.
        policy: the policy to start this iteration with (base on a fresh iteration 1).
        client: async client for the patient and oracle roles.
        cfg, gen, roles, oracle_cfg, la_cfg, paths: the frozen config bundle.
        primitives: the shared loop-keyed semaphores and GPU lock. It MUST be the one instance
            for the process -- TRL awaits the reward closure on its own event loop, and a
            semaphore cached anywhere else raises "attached to a different loop" partway into
            training.
        start_iteration / resume_checkpoint: from ``core.policy.resolve_start_state``. The
            checkpoint applies only to the first iteration of this process.
        cumulative_step_offset: steps completed in earlier iterations, for the live TB view.
        tb_logger: an optional ``core.tb.RunTBLogger``.
        server_handles / client_factory: see :func:`ensure_servers_alive`.
        skip_if_complete: when the adapter already exists, return without retraining.

    Returns:
        A dict with at least ``policy``, ``step_delta``, ``iteration``, ``skipped``, the phase
        seconds, the counts, and the look-ahead state summary. **``policy`` is the trained
        policy** and the caller must rebind it before the next iteration.

    Raises:
        RuntimeError: propagated from the reward function when the oracle success rate falls
            below ``min_success_ratio``, or from :func:`ensure_servers_alive` when a vLLM server
            exhausts its restart budget. Both mean "stop, do not train on this" -- the iteration
            resumes from its last checkpoint once the cause is fixed.

    Notes:
        **Resume, in three places.** Conversations already on disk are reloaded rather than
        regenerated; the HF trainer resumes from *resume_checkpoint*; and the EDA recorder is
        reloaded from the snapshot stored inside that checkpoint. The third is the one that is
        easy to forget: HF fast-forwards the batches it already consumed WITHOUT re-invoking the
        reward function, so without the reload this iteration's ``generations.jsonl`` would
        silently contain only the rows produced after the resume point -- a file that looks
        complete and is missing its first half.

        **``skip_if_complete`` does not reload the finished adapter into memory.** It returns the
        policy it was given, unchanged, and says so. The normal path never reaches it: the loop
        range comes from ``resolve_start_state``, which already skips completed iterations. It
        exists so that re-running a notebook cell cannot silently retrain and overwrite an
        adapter later iterations were built on.

        **One ``LookaheadState`` per iteration**, created here and handed to the reward factory.
        That is what makes the OOM sub-batch halving sticky across the iteration's optimizer
        steps instead of re-paying the OOM on every one of them, and it is what lets the realized
        sub-batch be recorded afterwards -- it is in no ``EXPERIMENT_NAME``, so a halving
        otherwise leaves no trace and per-iteration wall-clock quietly stops being comparable.
    """
    iter_start = time.time()
    iter_dir = paths.ensure_iteration_dir(iteration)

    print("\n" + "=" * 78)
    print(
        f"ITERATION {iteration}/{cfg.num_iterations}   {cfg.experiment_name}\n"
        f"  generating with model_iter_{iteration - 1}"
    )
    print("=" * 78)

    if skip_if_complete and validate_iteration_checkpoint(iter_dir):
        _warn(
            f"iteration_{iteration}/adapter already exists -- skipping. The in-memory policy was "
            f"NOT replaced by it; restart from core.policy.resolve_start_state if you need the "
            f"trained weights loaded."
        )
        return {
            "iteration": iteration,
            "skipped": True,
            "policy": policy,
            "step_delta": 0,
            "adapter_dir": paths.adapter_dir(iteration),
        }

    # -- 1. Generate -----------------------------------------------------------
    fresh = ensure_servers_alive(server_handles, client_factory=client_factory, phase="generate")
    if fresh is not None:
        client = fresh

    conv_dir = paths.ensure_conv_dir(iteration - 1)
    persona_ids = select_persona_ids(
        len(permutations), gen.num_conversations_per_iter, seed=cfg.seed, iteration=iteration
    )
    resuming_mid_training = bool(resume_checkpoint and iteration == start_iteration)
    if resuming_mid_training:
        # Mid-training resume: the crashed process already generated, extracted and SHUFFLED this
        # iteration's dataset, and HF resumes by a purely positional skip_first_batches. The
        # dataset must therefore be rebuilt from EXACTLY the conversations on disk -- generating
        # anything here (e.g. refilling a persona) would change the pool, re-deal the shuffle,
        # and misalign every fast-forwarded batch, while also filing this policy's output as
        # model_iter_{n-1} eval data.
        gen_start = time.time()
        loaded = load_conversations_dir(conv_dir, verbose=gen.verbose)
        states = [loaded[pid] for pid in sorted(loaded) if pid in set(persona_ids)]
        missing = sorted(set(persona_ids) - set(loaded))
        if missing:
            raise RuntimeError(
                f"mid-training resume of iteration_{iteration}: {len(missing)} persona CSV(s) "
                f"missing from {conv_dir} ({missing}). The crashed process trained on the full "
                f"set, so resuming on fewer would misalign the fast-forwarded batches. Restore "
                f"the files (check the Drive mount / cloud first) or delete "
                f"iteration_{iteration}/training/ to restart the iteration cleanly."
            )
        generation_s = time.time() - gen_start
        print(
            f"{_LOG}Mid-training resume: reloaded {len(states)} conversations from "
            f"{conv_dir} (no generation -- the dataset must match the crashed process's)"
        )
    else:
        states, generation_s = run_generation_phase(
            policy=policy,
            tokenizer=tokenizer,
            client=client,
            roles=roles,
            gen=gen,
            primitives=primitives,
            permutations=permutations,
            therapist_system_prompt=therapist_system_prompt,
            therapist_init_utterance=therapist_init_utterance,
            conv_dir=conv_dir,
            persona_ids=persona_ids,
            patient_seed=cfg.seed + iteration,
            label=f"iteration {iteration}",
        )
    avg_conv_len = (sum(s.n_utterances for s in states) / len(states)) if states else 0.0

    # Phase logged as it completes (never batched to iteration end): a process killed during
    # training must still leave its generation phase on record, or the cost axis undercounts
    # every preempted iteration. The per-process token keeps the session counters honest.
    log_session(
        iter_dir,
        generation_s=generation_s,
        started_at=iter_start,
        note=("reloaded for mid-training resume" if resuming_mid_training
              else f"generation, iteration {iteration}"),
    )

    # The generation KV caches are the largest thing alive right now, and the trainer is about to
    # allocate its own. Freeing between phases is not cosmetic: consecutive phases reach different
    # sequence lengths, so freed blocks are the wrong size to reuse.
    gc.collect()
    torch.cuda.empty_cache()

    # -- 2. Extract + split ----------------------------------------------------
    samples = extract_training_prompts(
        states,
        tokenizer=tokenizer,
        gen=gen,
        therapist_system_prompt=therapist_system_prompt,
        permutations=permutations,
    )
    train_dataset, eval_dataset = build_dataset(
        samples, eval_split_ratio=cfg.eval_split_ratio, seed=cfg.seed
    )

    # -- 3. Train --------------------------------------------------------------
    recorder = EDARecorder(
        paths.generations_path(iteration),
        enabled=cfg.save_eda_generations,
        save_transcripts=cfg.save_lookahead_transcripts,
    )
    if resume_checkpoint and iteration == start_iteration and recorder.enabled:
        n_loaded = recorder.load_from(os.path.join(resume_checkpoint, EDA_SNAPSHOT_FILENAME))
        if n_loaded:
            # make_reward_fn seeds its prompt-group counter from the recorder, so the post-resume
            # branch_ids continue past these rows instead of restarting at 0 and colliding with
            # them in the same generations.jsonl -- (conversation_id, branch_id) is the key the
            # EDA aggregates on, and a repeat pools two unrelated groups silently.
            print(
                f"{_LOG}Reloaded {n_loaded} EDA branch rows from "
                f"{os.path.basename(resume_checkpoint)} (HF fast-forwards skipped batches without "
                f"re-invoking the reward fn, so these would otherwise be lost); "
                f"branch_id resumes at {recorder.next_group_branch_id()}"
            )

    # The adapter is attached AFTER generation so model_iter_0 really is the untrained base, and
    # BEFORE the reward factory so the closure captures the object the trainer will train.
    policy = ensure_peft_policy(policy, cfg, tokenizer)

    lookahead_state = LookaheadState()
    reward_fn = make_reward_fn(
        policy,
        tokenizer,
        client,
        oracle_cfg,
        la_cfg,
        primitives,
        recorder=recorder,
        sp_therapist=therapist_system_prompt,
        iteration=iteration,
        num_generations=cfg.num_generations,
        lookahead_state=lookahead_state,
    )

    training_dir = paths.training_dir(iteration)
    tb_log_dir = os.path.join(training_dir, TB_SUBDIR)
    grpo_args = build_grpo_config(
        cfg,
        gen,
        output_dir=training_dir,
        num_train_prompts=len(train_dataset),
        has_eval=eval_dataset is not None,
        tb_log_dir=tb_log_dir,
        tokenizer=tokenizer,
    )
    metadata_base = _iteration_metadata_base(
        cfg=cfg, gen=gen, roles=roles, la_cfg=la_cfg, iteration=iteration
    )

    fresh = ensure_servers_alive(server_handles, client_factory=client_factory, phase="train")
    if fresh is not None:
        # The closure captured the old client; rebuild the reward fn against the live one.
        client = fresh
        reward_fn = make_reward_fn(
            policy, tokenizer, client, oracle_cfg, la_cfg, primitives,
            recorder=recorder, sp_therapist=therapist_system_prompt, iteration=iteration,
            num_generations=cfg.num_generations, lookahead_state=lookahead_state,
        )

    trainer, step_delta, training_s = run_training_phase(
        policy=policy,
        tokenizer=tokenizer,
        grpo_args=grpo_args,
        reward_funcs=reward_fn,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
        iteration=iteration,
        iter_metadata=metadata_base,
        recorder=recorder,
        resume_checkpoint=(resume_checkpoint if iteration == start_iteration else None),
        tb_log_dir=tb_log_dir,
    )
    new_policy = trainer.model
    del trainer  # the model stays alive through new_policy
    gc.collect()
    torch.cuda.empty_cache()

    # -- EDA + live TB ---------------------------------------------------------
    recorder.flush()
    if recorder.enabled:
        print(f"{_LOG}EDA generations -> {recorder.out_path} ({len(recorder)} branch rows)")

    end_step = int(cumulative_step_offset) + int(step_delta)
    if tb_logger is not None and len(recorder):
        scalars, scores = recorder.aggregate()
        scalars["iteration/num_prompts"] = float(len(samples))
        scalars["iteration/num_conversations"] = float(len(states))
        scalars["iteration/avg_conv_length"] = float(avg_conv_len)
        tb_logger.log_scalars(scalars, step=end_step, iteration=iteration)
        if scores:
            tb_logger.log_histogram(
                "eda/candidate_reward_hist", scores, step=end_step, iteration=iteration
            )
        samples_for_display = recorder.sample_for_display(cfg.tb_sample_completions_n)
        if samples_for_display:
            tb_logger.log_sample_completions(
                samples_for_display, step=end_step, iteration=iteration
            )

    # -- 4. Timing + save ------------------------------------------------------
    # The generation phase logged itself when it finished; this line records the training phase.
    # Logged BEFORE the metadata is built, so metadata_fields() sees this session too. Only what
    # THIS process did: the session log sums across processes, and double-counting a phase that a
    # previous session already recorded is exactly the failure it exists to prevent.
    log_session(
        iter_dir,
        training_s=training_s,
        started_at=iter_start,
        note=(
            f"training, resumed from {os.path.basename(resume_checkpoint)}"
            if resuming_mid_training
            else f"training, iteration {iteration}"
        ),
    )
    metadata = {
        **metadata_base,
        "num_conversations": len(states),
        "num_prompts": len(samples),
        "num_train_prompts": len(train_dataset),
        "num_eval_prompts": (len(eval_dataset) if eval_dataset is not None else 0),
        "avg_conversation_length": float(avg_conv_len),
        "epochs_per_iteration": cfg.epochs_per_iteration,
        "global_step_delta": int(step_delta),
        "cumulative_step_offset": int(cumulative_step_offset),
        "eda_branch_rows": len(recorder),
        # sub_batch is in no EXPERIMENT_NAME, so this record is the only place a run-time halving
        # is visible -- and per-iteration wall-clock is not comparable across different values.
        "lookahead_sub_batch": lookahead_state.sub_batch,
        "lookahead_gpu_calls": lookahead_state.gpu_calls,
        "lookahead_oom_events": lookahead_state.oom_events,
        "lookahead_runtime_errors": lookahead_state.runtime_errors,
        **metadata_fields(iter_dir),
    }
    adapter_dir = save_iteration_checkpoint(
        policy=new_policy,
        tokenizer=tokenizer,
        paths=paths,
        iteration=iteration,
        metadata=metadata,
    )
    push_adapter_to_hub(new_policy, cfg, iteration=iteration)

    elapsed = time.time() - iter_start
    print(
        f"\n{_LOG}Iteration {iteration} complete in {elapsed:.1f}s "
        f"({len(states)} conversations, {len(samples)} prompts, {step_delta} steps)\n"
        f"{_LOG}Look-ahead: {lookahead_state.summary()}"
    )
    print("=" * 78)

    return {
        "iteration": iteration,
        "skipped": False,
        "policy": new_policy,
        "step_delta": int(step_delta),
        "cumulative_step_offset": end_step,
        "conv_dir": conv_dir,
        "adapter_dir": adapter_dir,
        "n_conversations": len(states),
        "n_prompts": len(samples),
        "n_train_prompts": len(train_dataset),
        "n_eval_prompts": (len(eval_dataset) if eval_dataset is not None else 0),
        "avg_conv_length": float(avg_conv_len),
        "generation_s": generation_s,
        "training_s": training_s,
        "iteration_s": elapsed,
        "eda_branch_rows": len(recorder),
        "lookahead_state": lookahead_state,
        "client": client,
        "metadata": metadata,
    }


# ==============================================================================
#  Post-loop eval pass
# ==============================================================================


def run_final_eval(
    *,
    policy,
    tokenizer,
    client,
    cfg: GRPOTrainingConfig,
    gen: GenConfig,
    roles: RolesConfig,
    paths: RunPaths,
    primitives: AsyncPrimitives,
    permutations: Sequence[Dict[str, str]],
    therapist_system_prompt: str,
    therapist_init_utterance: str,
    server_handles: Optional[Mapping[str, Any]] = None,
    client_factory: Optional[Callable[[], Any]] = None,
) -> Dict[str, Any]:
    """Generate ``model_iter_{NUM_ITERATIONS}`` so the final adapter has matched eval data.

    Args:
        policy: the policy after the last iteration.
        cfg, gen, roles, paths, primitives, permutations, ...: as in
            :func:`run_one_iteration`.

    Returns:
        ``{"conv_dir", "n_conversations", "avg_conv_length", "eval_gen_s", "client"}``.

    Notes:
        **Why this pass exists.** Every trained iteration gets its eval conversations for free:
        iteration ``n`` generates with the iter-(``n``-1) policy, so those conversations ARE the
        eval set for model state ``n-1``. The LAST adapter never generates anything under that
        rule, so ``N`` iterations produce ``N`` conversation folders and the final policy has no
        measurement. This pass closes the gap, which is why ``N`` iterations yield ``N+1``
        folders.

        No prompts are extracted here -- nothing is going to be trained on them.

        **Idempotent.** ``generate_all_conversations`` skips personas whose CSVs already exist,
        so re-running this after a successful pass costs a directory listing.

        The timing is logged against ``iteration_{NUM_ITERATIONS}`` under the ``eval_gen_s``
        phase, because that is the iteration whose adapter produced these conversations. It is a
        separate phase key precisely so a cost analysis can exclude it from training cost without
        losing it.

    Raises:
        RuntimeError: when ``iteration_{NUM_ITERATIONS}/adapter/`` does not exist -- i.e. the loop
            did not finish. The label is the MODEL STATE, so on a short arm this would file an
            earlier policy's conversations as the final state and, via ``log_session``, mint an
            ``iteration_N/`` directory the EDA then reads as a real, zero-cost iteration.
    """
    label = int(cfg.num_iterations)
    completed = list_iteration_checkpoints(paths.run_dir)
    last_done = completed[-1][0] if completed else 0
    if last_done != label:
        raise RuntimeError(
            f"run_final_eval would label these conversations model_iter_{label}, but the last "
            f"COMPLETED iteration of {cfg.experiment_name} is {last_done} "
            f"({'no iteration finished' if not completed else f'iteration_{last_done}/adapter/'})."
            f" The label names the generating POLICY, so this pass would file iteration "
            f"{last_done}'s output as state {label} and mint an iteration_{label}/ directory that "
            f"the compute axis prices as a real, zero-cost iteration. Finish the loop, or set "
            f"NUM_ITERATIONS={last_done}. To measure a partial arm on purpose, use "
            f"tools/generate_convs.py, which refuses exactly this mismatch."
        )
    start = time.time()

    print("\n" + "=" * 78)
    print(f"FINAL EVAL PASS   model_iter_{label}   {cfg.experiment_name}")
    print("=" * 78)

    fresh = ensure_servers_alive(server_handles, client_factory=client_factory, phase="final eval")
    if fresh is not None:
        client = fresh

    # Same convention as Exp3: the post-loop pass draws its persona subset one step past the last
    # iteration, so it never reuses iteration N's shuffle.
    final_seed = cfg.seed + label + 1
    persona_ids = select_persona_ids(
        len(permutations), gen.num_conversations_per_iter, seed=cfg.seed, iteration=label + 1
    )
    conv_dir = paths.ensure_conv_dir(label)

    states, seconds = run_generation_phase(
        policy=policy,
        tokenizer=tokenizer,
        client=client,
        roles=roles,
        gen=gen,
        primitives=primitives,
        permutations=permutations,
        therapist_system_prompt=therapist_system_prompt,
        therapist_init_utterance=therapist_init_utterance,
        conv_dir=conv_dir,
        persona_ids=persona_ids,
        patient_seed=final_seed,
        label=f"final eval, model_iter_{label}",
    )
    n_states = len(states)
    avg_conv_len = (sum(s.n_utterances for s in states) / n_states) if n_states else 0.0

    log_session(
        paths.iteration_dir(label),
        eval_gen_s=seconds,
        started_at=start,
        note=f"final eval generate-only -> model_iter_{label}",
    )

    del states
    gc.collect()
    torch.cuda.empty_cache()

    print(f"{_LOG}Final eval conversations -> {conv_dir}")
    return {
        "conv_dir": conv_dir,
        "n_conversations": n_states,
        "n_requested": len(persona_ids),
        "avg_conv_length": float(avg_conv_len),
        "eval_gen_s": seconds,
        "client": client,
    }
